### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by louis030195** [webbertakken/unity-builder#104] opened 2020-06-15 16:22 UTC
License OK.
Unity  2020.1.0b12 beta

Probably because too recent unity version ? Tried to retrograde to LTS 2019 but it break my scenes (unable to load scenes ...).
Any idea to get more details or a solution ?

> ###########################
> #    Building platform    #
> ###########################
> 
> 
> [Licensing::Module] Channel doesn't exist: "LicenseClient-root"
> [Licensing::Module] Successfully launched the LicensingClient (PId: 74)
> [Licensing::Module] Successfully connected to LicensingClient on channel: "LicenseClient-root"
> [SignatureVerifier] Application signature verification not supported on this platform.
> Entitlement-based licensing initiated
> [LicensingClient] Licenses updated successfully
> Segmentation fault (core dumped)
> Build failed, with exit code 139

**Comment by webbertakken** [comment] 2020-06-15 19:30
This is a duplicate of https://github.com/webbertakken/unity-actions/issues/66 and https://github.com/webbertakken/unity-actions/issues/70

It's a bug in Unity running in docker.

**Closed** 2020-06-15 19:31 UTC
Labels: bug in unity, wontfix

**Comment by webbertakken** [comment] 2021-04-23 22:14
See also https://github.com/game-ci/unity-actions/issues/84
